// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fblyihcvrpbbjzkqbxwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibHlpaGN2cnBiYmp6a3FieHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTQ2MzcsImV4cCI6MjA2Mzg5MDYzN30.k2w__HBYKshXAcIybQZifCUpFR6C8srEAdaWJgLaz90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);